config/routes.rb
Rails.application.routes.draw do

root 'pages#home'
  
  get 'about' => 'pages#about'

  resources :signups

  get 'thanks' => 'pages#thanks'

end

app/models/signup.rb
class Signup < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

def home
end

def about
end

def thanks
end

end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController
  def new
    @signup = Signup.new
  end
  
  def create
    @signup = Signup.new (signup_params)
    if @signup.save
      redirect_to thanks_path
    else
      render 'new'
    end
  end
  
  private
  def signup_params
    params.require(:signup).permit(:firstname, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/signups_helper.rb
module SignupsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stories</title>
  <!-- Latest compiled and minified CSS -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" 
  <link href="https://fonts.googleapis.com/css2?family=Encode+Sans+SC:wght@100;300;500;700&display=swap" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>  
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="menu">
        <ul>
          <li><%= link_to "home", root_path %></li>
          <li><%= link_to "about", about_path %></li>
           <li><%= link_to "sign up", new_signup_path %></li>
        </ul>
    	<img alt="Close" class="icon-close" src="https://s3.amazonaws.com/codecademy-content/projects/z2d/stories/close-white.svg" width="24px">
    </div>
  <img alt="Open" class="icon-menu" src="https://s3.amazonaws.com/codecademy-content/projects/z2d/stories/menu-white.svg" width="24px">

	<%= yield %>
  <div class="footer">
  <div class="container">
    <p>@ 2021 NABSBELLE Projects</p>
  </div>
</div>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/pages/about.html.erb
<div class="about-main">
  <div class="content container">
    <h1>World New Adventures</h1>
  </div>
</div>
<div class="about-supporting">
  <div class="container">
    <h2>Get into my Stories</h2>
    <p>Relive. Smooth. Wild. Peaceful.</p>
    <p><%= link_to "sign up", new_signup_path, class: "btn btn-primary" %></p>
  </div>
</div>

app/views/pages/home.html.erb
<div class="home-main">
  <div class="container">
		<div class="row">
      <div class="content cold-md-6 col-md-offset-6">
        <h1>World New Adventures</h1>
        <p><%= link_to "Learn more", about_path, class: "btn btn-primary" %></p>
      </div>
    </div>
  </div>
</div>
<div class="home-supporting">
  <div class="container">
    <h2>Get into my Stories</h2>
    <p>Relive. Smooth. Wild. Peaceful.</p>
  </div>
</div>
<div class="home-secondary">
  <div class="container">
  </div>
</div>
<div class="home-about">
  <div class="container">
    <h2>World is not enough. We need Universe.</h2>
    <p><%= link_to "Learn more", about_path, class: "btn btn-primary" %></p>
  </div>
</div>

app/views/pages/thanks.html.erb
<div class="contact-main">
  <div class="content container">
    <h1>Thank You. We'll be in touch.</h1>
  </div>
</div>

app/views/signups/new.html.erb
<div class="contact-main">
  <div class="content container">
    <h1>Get the latest updates</h1>
    <div class="row">
      <div class="col-md-4 col-md-4-offset"></div>
      <div class="col-md-4">
        <%= form_for(@signup) do |f| %>
        <div class="field">
          <div class="form-group">
            <%= f.label :firstname, "first name" %><br>
            <%= f.text_field :firstname, class: "form-control" %><br>
          </div>
          <div class="form-group">
            <%= f.label :email, "email" %><br>
					<%= f.text_field :email, class: "form-control" %><br>
          </div>
        </div>
        <div class="actions">
          <%= f.submit "join", class: "btn btn-default" %>
        </div>
        <% end %>
      </div>
    </div>
    <div class="col-md-4 col-md-4-offset">
    </div>
  </div>
</div>